# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'POC-VM'
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/*.war'
    targetFolder: '/home/microsoft/apache-tomcat-9.0.64/webapps'
    readyTimeout: '20000'
    flattenFolders: true
- task: SSH@0
  inputs:
    sshEndpoint: 'POC-VM'
    runOptions: 'inline'
    inline: |
      /home/microsoft/apache-tomcat-9.0.64/bin/shutdown.sh
      /home/microsoft/apache-tomcat-9.0.64/bin/startup.sh
    readyTimeout: '20000'